# cloudbuild.yaml
steps:
  # 1) Build and push the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/luxury-bot', '.']

  # 2) Deploy to Cloud Run (updates the service)
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'luxury-bot',
        '--image', 'gcr.io/$PROJECT_ID/luxury-bot',
        '--region', 'us-central1',
        '--platform', 'managed',
        '--allow-unauthenticated'
      ]

images:
  - 'gcr.io/$PROJECT_ID/luxury-bot'
