import groq
import gspread
from oauth2client.service_account import ServiceAccountCredentials
from datetime import datetime

# === CONFIG ===
groq_client = groq.Groq(api_key="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")  # 🔁 Replace with your real key

# Google Sheets setup
scope = ["https://spreadsheets.google.com/feeds", "https://www.googleapis.com/auth/drive"]
creds = ServiceAccountCredentials.from_json_keyfile_name("creds.json", scope)
client = gspread.authorize(creds)

sheet = client.open_by_key("1PTTeJhjyo2L9MxSMslhror_SNclAgEPVY97Cb1FETrQ").sheet1

# === QUOTE GENERATION ===
def generate_quote():
    prompt = (
        "Give me a short luxury or elite motivational quote (max 15 words). "
        "Avoid clichés. It should feel high-end, exclusive, and powerful."
    )
    response = groq_client.chat.completions.create(
        model="llama3-8b-8192",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.7
    )
    return response.choices[0].message.content.strip().strip('"')

# === CAPTION GENERATION ===
def generate_caption(quote):
    prompt = f"Write an Instagram caption for this luxury quote:\n\n\"{quote}\"\n\nKeep it elite, 20 words max, include an emoji."
    response = groq_client.chat.completions.create(
        model="llama3-8b-8192",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.7
    )
    return response.choices[0].message.content.strip()

# === WRITE TO SHEET ===
def log_to_sheet(quote, caption):
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    video_url = "https://example.com/luxury-video.mp4"  # placeholder until Pexels fills it
    sheet.append_row([now, quote, caption, video_url, "Pending", "Generated by Groq"])
    print("✅ Quote inserted:", quote)

# === MAIN ENTRY ===
def main():
    quote = generate_quote()
    caption = generate_caption(quote)
    log_to_sheet(quote, caption)

if __name__ == "__main__":
    main()
